spring:
  application:
    name: marketplace

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    properties:
      sslmode: ${SPRING_R2DBC_SSL_MODE:prefer}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-life-time: 30m

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true

  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    org.springframework.r2dbc: INFO
    org.springframework.data.r2dbc: INFO
    io.r2dbc.postgresql: INFO
